package com.weekendplanner.engine;

public enum RecentEventType {
    PLAN_CREATED,
    CANDIDATES_RECOMMENDED,
    CHOICE_BAR_RENDERED,
    CANDIDATE_SELECTED,
    PREFERENCE_SELECTED,
    CONTEXT_UPDATED,
    TIME_EXTENDED,
    PENDING_CANCELLED
}
